# Generated by Django 4.0.3 on 2023-02-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track_expense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gmail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
            ],
        ),
    ]
